openapi: 3.1.0
info:
  version: 0.0.1
  title: eXtended Finite State Machine APIs
  description: These APIs allows to interact with an existing XFSM bag and retrieve statistics
servers:
  - url: 'http://todo.url'
    description: Sample
paths:
  /stats:
    get:
      tags:
        - 'statistics, all'
      summary: Retrieves statistics for the current bag (total, tot. errors, ...)
      responses:
        '200':
          description: The bag statistics.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/statistic'
  /errors:
    get:
      tags:
        - 'errors, all'
      summary: Retrieves all the elements still in error
      parameters: 
        - name: "top"
          in: "query"
          required: false
          allowEmptyValue: false
          description: "Top N elements to retrieve"
          schema:
            type: number
            format: int32
            default: 10
        - name: "index"
          in: "query"
          required: true
          allowEmptyValue: false
          description: "The zero based page index to retrieve"
          schema:
            type: number
            format: int32
            default: 0
      responses:
        '200':
          description: The first N elements in error.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/statistic'
components:
  schemas:
    statistic:
      type: object
      properties:
        total:
          description: "Overall total amount of elements"
          type: integer
          format: int32
        errors:
          description: "Total amount of elements currently in an error status"
          type: integer
          format: int32
        business:
          description: "Overall total of grouped elements by business xfsm status"
          type: array
          items:
            type: object
            properties:
              state:
                description: "The specific grouped business xfsm status"
                type: integer
                format: int32
              count:
                description: "The count of elements having that specified state"
                type: integer
                format: int32
