openapi: 3.1.0
info:
  version: 0.0.1
  title: eXtended Finite State Machine APIs
  description: These APIs allows to interact with an existing XFSM bag and retrieve statistics
servers:
  - url: 'http://todo.url'
    description: Sample
paths:
  /stats:
    get:
      tags:
        - 'statistics'
      summary: Retrieves statistics for the current bag (total, tot. errors, ...)
      responses:
        '200':
          description: The bag statistics.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/statistic'
  /errors:
    get:
      tags:
        - 'errors'
      summary: Retrieves all the elements still in error
      parameters: 
        - name: "top"
          in: "query"
          required: false
          allowEmptyValue: false
          description: "Top N elements to retrieve"
          schema:
            type: number
            format: int32
            default: 10
        - name: "index"
          in: "query"
          required: true
          allowEmptyValue: false
          description: "The zero based page index to retrieve"
          schema:
            type: number
            format: int32
            default: 0
      responses:
        '200':
          description: The first N elements in error.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/statistic'
  /next:
    get:
      tags:
        - 'process'
      summary: Retrieves next element to be processed
      parameters: 
        - name: "mode"
          in: "query"
          required: true
          allowEmptyValue: false
          description: "The peek mode (queue, stack)"
          schema:
            type: string
            enum: [queue, stack]
      responses:
        '200':
          description: The bag retrieve the next element to be processed, if any.
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/bag-element'
        '204':
          description: No new element to be processed.
  /{id}/done:
    put:
      tags:
        - 'process'
      summary: Set the specific element as processed
      parameters: 
        - name: "id"
          in: "path"
          required: true
          allowEmptyValue: false
          description: "The bag element id"
          schema:
            type: number
            format: int64
      responses:
        '201':
          description: The element has been set as processed.
        '404':
          description: The specified id does not exists.
  /{id}/change-status/{state}:
    put:
      tags:
        - 'process'
      summary: Change state on the specified bag element
      parameters: 
        - name: "id"
          in: "path"
          required: true
          allowEmptyValue: false
          description: "The bag element id"
          schema:
            type: number
            format: int64
        - name: "state"
          in: "path"
          required: true
          allowEmptyValue: false
          description: "The new state to set on the bag element id"
          schema:
            type: number
            format: int32
      responses:
        '200':
          description: "Returns the new element id"
          content:
            application/json:
              schema:
                type: number
                format: int32
        '404':
          description: The specified id does not exists.
  /{id}/error:
    put:
      tags:
        - 'process'
      summary: Set the specific element as processed
      requestBody:
        required: true
        description: "The error message"
        content:
          text/plain:
            schema:
              type: string
      parameters: 
        - name: "id"
          in: "path"
          required: true
          allowEmptyValue: false
          description: "The bag element id"
          schema:
            type: number
            format: int64
      responses:
        '201':
          description: The element has been set as processed.
        '404':
          description: The specified id does not exists.
  /add:
    post:
      tags:
        - 'process'
      summary: Add a new element to the bag
      requestBody:
        required: true
        description: "The business element to add into the bag"
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/bag-element'
      responses:
        '200':
          description: "Returns the new element id"
          content:
            application/json:
              schema:
                type: number
                format: int32
components:
  schemas:
    statistic:
      type: object
      properties:
        total:
          description: "Overall total amount of elements"
          type: integer
          format: int32
        errors:
          description: "Total amount of elements currently in an error status"
          type: integer
          format: int32
        business:
          description: "Overall total of grouped elements by business xfsm status"
          type: array
          items:
            type: object
            properties:
              state:
                description: "The specific grouped business xfsm status"
                type: integer
                format: int32
              count:
                description: "The count of elements having that specified state"
                type: integer
                format: int32
    bag-element:
      type: object
      properties:
        id:
          description: "Bag id"
          type: integer
          format: int64
        element:
          description: "The business element"
          type: object
